name: Build exe

on:
  push:
    branches:
      - main  # 或者是你的默认分支

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller --onefile 444.py  # 用你的Python脚本文件名替换your_script.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-file
        path: ./dist/444.exe  # 用你的Python脚本文件名替换your_script
